#!/usr/bin/env bash
set -euo pipefail

CONFIRM_HSD_SYNC="${CONFIRM_HSD_SYNC:-0}"
DRY_RUN="${DRY_RUN:-0}"
HSD_READY_ATTEMPTS="${HSD_READY_ATTEMPTS:-360}"
HSD_READY_INTERVAL_SECONDS="${HSD_READY_INTERVAL_SECONDS:-60}"
INDEXER_FINAL_ACTION="${INDEXER_FINAL_ACTION:-stop}"
INDEXER_FAILURE_ACTION="${INDEXER_FAILURE_ACTION:-stop}"

if [ "$CONFIRM_HSD_SYNC" != "1" ] && [ "$DRY_RUN" != "1" ]; then
  cat >&2 <<EOF
Refusing to start the indexer for HSD sync without CONFIRM_HSD_SYNC=1.

Review the plan first:
  DRY_RUN=1 $0

Then run explicitly:
  CONFIRM_HSD_SYNC=1 $0

EOF
  exit 2
fi

CONFIRM_PRODUCTION_RUN=1 \
DRY_RUN="$DRY_RUN" \
WAIT_FOR_HSD_READY=1 \
HSD_READY_ATTEMPTS="$HSD_READY_ATTEMPTS" \
HSD_READY_INTERVAL_SECONDS="$HSD_READY_INTERVAL_SECONDS" \
RUN_PIPELINE=0 \
RUN_PUBLISH=0 \
INDEXER_FINAL_ACTION="$INDEXER_FINAL_ACTION" \
INDEXER_FAILURE_ACTION="$INDEXER_FAILURE_ACTION" \
scripts/gcloud-production-cycle.sh
